
FROM public.ecr.aws/tibcolabs/labs-air-flogo-builder:1.16-alpine AS flogobuilder

ARG app_type

RUN apk update && apk add ca-certificates
RUN apk --update add bash

RUN set -ex && \
    apk add --no-cache gcc musl-dev

RUN set -ex && \
    rm -f /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/cc1obj && \
    rm -f /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/lto1 && \
    rm -f /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/lto-wrapper && \
    rm -f /usr/bin/x86_64-alpine-linux-musl-gcj

RUN mkdir ./genericApp
RUN cp ./create_build.sh ./genericApp
COPY airpipeline_oss/flogo-generic.json ./genericApp
COPY airpipeline_oss/build-generic.sh ./genericApp

WORKDIR ./genericApp
RUN chmod a+x build-generic.sh
#RUN ./build-generic.sh flogo-generic.json

CMD ["bash"]