###################################################################################
#                         Flogo App image                         #
###################################################################################
From python:3.9-alpine
    
RUN apk update && apk add ca-certificates

RUN apk add --update make cmake gcc g++ gfortran

RUN apk add bash

RUN pip install --upgrade pip

CMD ["bash.sh"]