# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pipecoupler_pb2 as pipecoupler__pb2


class PipeCouplerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HandleData = channel.unary_unary(
        '/pipecoupler.PipeCoupler/HandleData',
        request_serializer=pipecoupler__pb2.Data.SerializeToString,
        response_deserializer=pipecoupler__pb2.Reply.FromString,
        )


class PipeCouplerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def HandleData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PipeCouplerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HandleData': grpc.unary_unary_rpc_method_handler(
          servicer.HandleData,
          request_deserializer=pipecoupler__pb2.Data.FromString,
          response_serializer=pipecoupler__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pipecoupler.PipeCoupler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
