FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

# Install base utilities
#RUN apt-get update
#RUN apt-get upgrade
#RUN apt-get install -y build-essential
#RUN apt-get install -y wget
#RUN apt-get clean
#RUN rm -rf /var/lib/apt/lists/*

# Install miniconda
#ENV CONDA_DIR /opt/conda
#RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
#     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
#ENV PATH=$CONDA_DIR/bin:$PATH

#RUN conda install pytorch cudatoolkit=10.1 -c pytorch

RUN conda install -y opencv

RUN apt-get update

RUN pip install --upgrade pip
RUN pip install Flask
RUN pip install Flask-RESTful
RUN pip install waitress

COPY ./server /app

WORKDIR /app

RUN pip install -r requirements.txt

CMD ["python","-u","./server.py"]

EXPOSE 10010