# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipecoupler.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pipecoupler.proto',
  package='pipecoupler',
  syntax='proto3',
  serialized_options=b'\n\022com.tibco.modelopsB\020PipeCouplerProtoP\001',
  serialized_pb=b'\n\x11pipecoupler.proto\x12\x0bpipecoupler\"3\n\x04\x44\x61ta\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"D\n\x05Reply\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\x32\x44\n\x0bPipeCoupler\x12\x35\n\nHandleData\x12\x11.pipecoupler.Data\x1a\x12.pipecoupler.Reply\"\x00\x42(\n\x12\x63om.tibco.modelopsB\x10PipeCouplerProtoP\x01\x62\x06proto3'
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='pipecoupler.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='pipecoupler.Data.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='pipecoupler.Data.ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='pipecoupler.Data.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=85,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='pipecoupler.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='pipecoupler.Reply.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='pipecoupler.Reply.ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='pipecoupler.Reply.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='pipecoupler.Reply.status', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'pipecoupler_pb2'
  # @@protoc_insertion_point(class_scope:pipecoupler.Data)
  })
_sym_db.RegisterMessage(Data)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'pipecoupler_pb2'
  # @@protoc_insertion_point(class_scope:pipecoupler.Reply)
  })
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_PIPECOUPLER = _descriptor.ServiceDescriptor(
  name='PipeCoupler',
  full_name='pipecoupler.PipeCoupler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=157,
  serialized_end=225,
  methods=[
  _descriptor.MethodDescriptor(
    name='HandleData',
    full_name='pipecoupler.PipeCoupler.HandleData',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PIPECOUPLER)

DESCRIPTOR.services_by_name['PipeCoupler'] = _PIPECOUPLER

# @@protoc_insertion_point(module_scope)
