// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pipecoupler.proto

package com.tibco.modelops.grpc;

public final class PipeCouplerProto {
  private PipeCouplerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pipecoupler_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pipecoupler_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pipecoupler_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pipecoupler_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021pipecoupler.proto\022\013pipecoupler\"3\n\004Data" +
      "\022\016\n\006sender\030\001 \001(\t\022\n\n\002ID\030\002 \001(\t\022\017\n\007content\030" +
      "\003 \001(\t\"D\n\005Reply\022\016\n\006sender\030\001 \001(\t\022\n\n\002ID\030\002 \001" +
      "(\t\022\017\n\007content\030\003 \001(\t\022\016\n\006status\030\004 \001(\0102D\n\013P" +
      "ipeCoupler\0225\n\nHandleData\022\021.pipecoupler.D" +
      "ata\032\022.pipecoupler.Reply\"\000B-\n\027com.tibco.m" +
      "odelops.grpcB\020PipeCouplerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pipecoupler_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pipecoupler_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pipecoupler_Data_descriptor,
        new java.lang.String[] { "Sender", "ID", "Content", });
    internal_static_pipecoupler_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pipecoupler_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pipecoupler_Reply_descriptor,
        new java.lang.String[] { "Sender", "ID", "Content", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
